# Generated by Django 3.1.4 on 2020-12-27 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocerystore', '0002_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='cashier',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='grocerystore.staff'),
        ),
    ]
