# Generated by Django 3.1.4 on 2021-06-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerystore', '0003_check_cashier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyaltycard',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='loyaltycard',
            name='email',
            field=models.CharField(default='default name', max_length=150),
        ),
    ]
